# Birds CUB dataset
birds_dataset_path: 'D:\_Users\Pietruszynski\Text2Image\datasets\ee285f-public\caltech_ucsd_birds\birds.hdf5'

# flowers dataset
flowers_dataset_path: 'D:\_Users\Pietruszynski\Text2Image\datasets\ee285f-public\oxford_flowers\flowers.hdf5'